name: yt_dlp_gui
description: A cross-platform gui for yt-dlp.
version: 2.0.0+1
homepage: https://github.com/UA-99/yt-dlp-gui


environment:
  sdk: ^3.9.0

dependencies:
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/yt-dlp/win/
    - assets/yt-dlp/linux/
